# Generated by Django 4.2.1 on 2023-10-27 16:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('number_in_dict', models.IntegerField(default=0)),
                ('word', models.CharField(max_length=30, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Incorrect eng key word', regex='([A-Za-z]){1,30}')])),
                ('ru_word', models.CharField(blank=True, max_length=100)),
                ('ads_count_policy', models.PositiveIntegerField(blank=True, null=True)),
                ('ads_count_all', models.PositiveIntegerField(blank=True, null=True)),
                ('is_collected', models.BooleanField(default=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='countries.language')),
            ],
            options={
                'ordering': ['number_in_dict'],
            },
        ),
    ]
