# Generated by Django 4.2.1 on 2023-10-27 16:48

import django.core.validators
from django.db import migrations, models
from countries.models import get_pk


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='word',
            field=models.CharField(max_length=30, validators=[
                django.core.validators.RegexValidator(message='Incorrect eng key word', regex='([A-Za-z]){1,30}')]),
        ),
        migrations.AddField(
            model_name='keyword',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=True,
        ),

        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together={('word', 'language')},
        ),
    ]
