# Generated by Django 4.2.1 on 2023-09-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('port', models.CharField(max_length=6)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=None, max_length=50, null=True)),
                ('error_text', models.CharField(blank=True, max_length=255)),
                ('protocol', models.CharField(choices=[('http', 'http'), ('https', 'https'), ('socks5', 'socks5')], default='http', max_length=10)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('ip', 'port')},
            },
        ),
    ]
