# Generated by Django 4.2.1 on 2023-10-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0003_remove_proxy_login_remove_proxy_password_proxymobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='proxy_ip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='proxyauth',
            name='proxy_ip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='proxymobile',
            name='proxy_ip',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
