# Generated by Django 4.2.1 on 2023-10-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0005_remove_proxy_error_text_remove_proxyauth_error_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='ip',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='proxyauth',
            name='ip',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='proxymobile',
            name='ip',
            field=models.CharField(max_length=30),
        ),
    ]
