# Generated by Django 4.2.1 on 2023-10-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0006_alter_proxy_ip_alter_proxyauth_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='ip',
            field=models.CharField(max_length=30, verbose_name='ip/host'),
        ),
        migrations.AlterField(
            model_name='proxyauth',
            name='ip',
            field=models.CharField(max_length=30, verbose_name='ip/host'),
        ),
        migrations.AlterField(
            model_name='proxymobile',
            name='ip',
            field=models.CharField(max_length=30, verbose_name='ip/host'),
        ),
    ]
