# Generated by Django 4.2.1 on 2023-11-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('name', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('core', models.PositiveIntegerField()),
                ('ram', models.PositiveIntegerField()),
                ('os', models.CharField(choices=[('Windows', 'Windows'), ('Linux', 'Linux')], max_length=50)),
            ],
        ),
    ]
