# Generated by Django 4.2.1 on 2023-11-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_pc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ds',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
