# Generated by Django 4.2.1 on 2023-11-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_pc', '0002_ds_last_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ds',
            options={'verbose_name': 'DS', 'verbose_name_plural': 'DS'},
        ),
        migrations.AlterField(
            model_name='ds',
            name='name',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
