# Generated by Django 4.2.1 on 2023-12-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_pc', '0005_alter_ds_options_ds_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ds',
            name='use_in_pars',
            field=models.BooleanField(default=True),
        ),
    ]
