# Generated by Django 4.2.1 on 2024-01-29 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remote_pc', '0006_ds_use_in_pars'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField()),
                ('unique', models.PositiveIntegerField()),
                ('new', models.PositiveIntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('ds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remote_pc.ds')),
            ],
            options={
                'unique_together': {('ds', 'created')},
            },
        ),
    ]
