# Generated by Django 4.2.1 on 2023-09-25 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proxies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('mail_password', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('work', 'Рабочий'), ('ban', 'Бан')], default='work', max_length=50)),
                ('cookie_file', models.FileField(blank=True, upload_to='cookies')),
                ('created', models.DateField(auto_now_add=True)),
                ('use_in_work', models.BooleanField(default=True)),
                ('is_cookie_file_valid', models.BooleanField(default=None, null=True)),
                ('is_cookie_auth', models.BooleanField(default=None, null=True)),
                ('proxy', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proxies.proxy')),
            ],
        ),
    ]
