# Generated by Django 4.2.1 on 2023-09-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbaccount',
            name='check_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fbaccount',
            name='status',
            field=models.CharField(choices=[('work', 'Рабочий'), ('ban', 'Бан'), ('no_password', 'Нет пароля')], default='work', max_length=50),
        ),
    ]
