# Generated by Django 4.2.1 on 2023-09-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_fbaccount_check_text_alter_fbaccount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbaccount',
            name='cookie_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
