# Generated by Django 4.2.1 on 2023-09-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_fbaccount_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbaccount',
            name='user_agent',
            field=models.CharField(default='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36', max_length=255),
        ),
    ]
