# Generated by Django 4.2.1 on 2023-09-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_fbpagexample'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbgroup',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
