# Generated by Django 4.2.1 on 2023-09-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_fbgroup_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbpagexample',
            name='orig_url',
            field=models.URLField(blank=True),
        ),
    ]
