# Generated by Django 4.2.1 on 2023-09-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_fbpagexample_is_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbpagexample',
            name='type',
            field=models.CharField(blank=True, choices=[('fb_group', 'Группа'), ('fb_main', 'Главная')], max_length=30),
        ),
    ]
