# Generated by Django 4.2.1 on 2023-10-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_fbpagexample_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('pattern', models.CharField(max_length=30)),
            ],
        ),
    ]
