# Generated by Django 4.2.1 on 2023-10-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_mailservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbgroup',
            name='followers',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
