# Generated by Django 4.2.1 on 2023-10-16 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0013_alter_keyword_options_alter_keyword_ads_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['-ads_count_all', '-ads_count_policy']},
        ),
        migrations.RenameField(
            model_name='keyword',
            old_name='ads_count',
            new_name='ads_count_all',
        ),
        migrations.AddField(
            model_name='keyword',
            name='ads_count_policy',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='word',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Incorrect eng key word', regex='([A-Za-z]){1,30}')]),
        ),
    ]
