# Generated by Django 4.2.1 on 2023-10-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_alter_keyword_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailservice',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
    ]
