# Generated by Django 4.2.1 on 2023-10-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0015_mailservice_ignore'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoredMailGeo',
            fields=[
                ('domain', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='IgnoreGroupWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
