# Generated by Django 4.2.1 on 2023-10-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0017_fbgroup_is_ignore_word_mark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fbgroup',
            name='is_ignore_word_mark',
        ),
        migrations.AddField(
            model_name='fbgroup',
            name='is_ignore_word',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
