# Generated by Django 4.2.1 on 2023-10-19 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0019_keyword_number_in_dict_keyword_ru_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='id',
        ),
        migrations.AddField(
            model_name='keyword',
            name='is_collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='word',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Incorrect eng key word', regex='([A-Za-z]){1,30}')]),
        ),
    ]
