# Generated by Django 4.2.1 on 2023-10-20 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0020_remove_keyword_id_keyword_is_collected_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['number_in_dict']},
        ),
    ]
